# Setup
title:        WhatsApp Plus 2019 Download v6.82 for Android
tagline:      WhatsApp Plus 2019 Download Latest Version for Android.
baseurl:      "https://wpplus2019.xyz"
paginate:     1
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
